[package]
name = "cfind"
version = "0.1.0"
authors = ["spidax <spidax1881@gmail.com>"]
edition = "2018"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3


[dependencies]
term = "*"
structopt = "0.3.13"
